### ISSUE TITLE
Tag a release, please

### ISSUE THREAD

**Issue by seregazhuk** [WyriHaximus/reactphp-child-process-psr-3#1]
Are you planning to tag a release? Now, I have manually added repo to my composer.json, but it would be nice to have at least one version available 👍  Even "Installation" section in Reame says that I can use `composer require`.

**Comment by WyriHaximus** [comment]
Sure thing! Just tagged [`1.0.0`](https://github.com/WyriHaximus/reactphp-child-process-psr-3/releases/tag/1.0.0) but it's missing a bit of info in the readme. Fancy making a PR for that?

**Comment by WyriHaximus** [comment]
P.S. I copy paste my bare readme's and they always include that :zipper_mouth_face:

**Comment by seregazhuk** [comment]
That's great! Thank you 👍
