### ISSUE TITLE
Update wyrihaximus/react-child-process-messenger to 3.x

### ISSUE THREAD

**Issue by bartvanhoutte** [WyriHaximus/reactphp-child-process-psr-3#40]
Hoi Cees-Jan,

I've forked the repo and tried updating `wyrihaximus/react-child-process-messenger` to v3+ but I haven't been able to make the tests pass (looks like this goes a bit above my head). Do you have any plans on releasing an update soon?

**Comment by WyriHaximus** [comment]
Hey @bartvanhoutte, yes, I've been adding PHP 8 support to all these packages, so a new release will come within days, maybe hours depending on how smooth it goes

**Comment by WyriHaximus** [comment]
@bartvanhoutte Started working on it in #41

**Comment by WyriHaximus** [comment]
Just released [`2.0.0`](https://github.com/WyriHaximus/reactphp-child-process-psr-3/releases/tag/2.0.0), a PHP 8 supporting version will follow when messenger 3.1 with PHP 8 support is out.

**Comment by bartvanhoutte** [comment]
Excellent. Thanks @WyriHaximus, I'll test it today and will circle back if anything does't work.
